### ISSUE TITLE
CPT v0.3.7 has patch file typo and appears to be using old tree structure of PicoPort

### ISSUE THREAD

**Issue by Jacke4913** [yalov/CommunityPartsTitles#5]
Windows 10 1803
KSP 1.6.1
CKAN 1.25.4
CPT v0.3.7

PicoPort (as well as the other SHED mod REKT) aren't installed, but the SHED directory tree is still there due to two leftover MiniAVC.dll.pruned.

Link to zip with full logs as well as copy of CPT patch file for PicoPort and my mostly empty SHED directory tree.

https://www.dropbox.com/s/sd9qgmrwpbye3e6/20190204d.MM-SHED-Patches.zip?dl=1

I've looked at this issue and found a typo in a CPT patch file.  But I also think that the CPT patch is using the old directory tree structure for PicoPort.

Perhaps you may want to talk to @linuxgurugamer, maintainer of PicoPort as well.

WHAT HAPPENED

After CKAN upgraded to the new Community Parts Titles today, restarted KSP and got a Module Manager warning about it.

`[WRN 2019-02-04 23:36:28.288] 1 warning related to GameData/002_CommunityPartsTitles/localization/en-us_patch_picoport.cfg`

Found what the warning was about.  First the log warning then the en-us_patch_picoport typo.

`[LOG 2019-02-04 23:36:24.411] Deleting root node in file 002_CommunityPartsTitles/localization/en-us_patch_picoport node: @PART[dockingPort3Basic]:AFTER[SHED]:NEEDS[SHED/Patches] as it can't satisfy its NEEDS`
`[WRN 2019-02-04 23:36:24.411] extra : detected`
`[LOG 2019-02-04 23:36:24.411] Deleting root node in file 002_CommunityPartsTitles/localization/en-us_patch_picoport node: @PART[dockingPort2M]::AFTER[SHED]:NEEDS[SHED/Patches] as it can't satisfy its NEEDS`

`@PART[dockingPort2M]::AFTER[SHED]:NEEDS[SHED/Patches]           { @title = Clamp-O-Tron Docking Port Mr. 'M'       } // Clamp-O-Tron Docking Port 'M'  `  

Almost missed it.  In fact, I noticed the issue with the directory tree before I found the warning about the extra ':'.

The SHED directory tree change.  @linuxgurugamer recently changed it to disentangle the two mods, PicoPort and REKT, which were both directly in GameData/SHED/.  They are now in GameData/SHED/PicoPort/ and GameData/SHED/REKT/ respectively.

But the CPT patch still says "NEEDS[SHED/Patches]" for PicoPort patches, which is only true for earlier PicoPort releases.  For recent ones, I think it should say "NEEDS[SHED/PicoPort/Patches"

Anyhoo, hope this helps.

**Comment by yalov** [comment]
thank for the extra ":" warning, will fix that

The mod "PicoPort for all sizes" v0.1.2.3 from the CKAN installs to `GameData/SHED/Patches` that why I need 
`:NEEDS[SHED/Patches]` and since "PicoPort for all sizes" is also patches I need also `:AFTER`, but `:AFTER` doesn't support subfolders, so I need `:AFTER[SHED]:NEEDS[SHED/Patches]` 

All other are ok, and in this case empty PicoPort and REKT doesn't interfere with CPT:
it hadn't found SHED/Patches so ignored this MM patches.

But you can delete leftover MiniAVCs, which is detected by MM as installed PicoPort and RECT, that can make trouble for other mods
